### PR TITLE
Add C++ layers for DetectNet

### PR DESCRIPTION
**Pull request by lukeyeager**

### CODE REVIEW

**Comment by lukeyeager** [comment]
Files renamed:

```
nv_transformer -> layers/detectnet_transform_layer
util/coverage_nv -> util/detectnet_coverage
util/rectangular_coverage_nv -> util/detectnet_coverage
```

Prototxt parameters renamed:

```
NVGroundTruthParameter -> DetectNetGroundTruthParameter
NVAugmentationParameter -> DetectNetAugmentationParameter
```

/cc @drendleman - any problem with this?

**Comment by drendleman** [comment]
DetectNet sounds fine to me. More precise

David

On May 13, 2016 11:55 AM, Luke Yeager notifications@github.com wrote:

Files renamed:

nv_transformer -> layers/detectnet_transform_layer
util/coverage_nv -> util/detectnet_coverage
util/rectangular_coverage_nv -> util/detectnet_coverage

Prototxt parameters renamed:

NVGroundTruthParameter -> DetectNetGroundTruthParameter
NVAugmentationParameter -> DetectNetAugmentationParameter

/cc @drendlemanhttps://github.com/drendleman - any problem with this?

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHubhttps://github.com/lukeyeager/caffe/pull/2#issuecomment-219130114

---

This email message is for the sole use of the intended recipient(s) and may contain
confidential information.  Any unauthorized review, use, disclosure or distribution
is prohibited.  If you are not the intended recipient, please contact the sender by

## reply email and destroy all copies of the original message.

**Comment by lukeyeager** [comment]
Slight update:

``` sh
# header
util/coverage_nv.hpp -> util/detectnet_coverage.hpp
# source
util/rectangular_coverage_nv.cpp -> util/detectnet_coverage_rectangular.cpp
```

**Comment by lukeyeager** [comment]
~~@ssarathy I'm going to rip the `visualize` and `img_headers` stuff out of there, too.~~

Nevermind, I'll leave it in.

**Comment by lukeyeager** [comment]
TravisCI problems:
- The code doesn't pass lint
  - I can disable it in CMake, but I can't figure out how to do it for the raw Makefile build
- The code doesn't compile on Ubuntu 12.04, apparently because OpenCV 2.3 is too old
  - https://travis-ci.org/lukeyeager/caffe/builds/130726363

So, we'll just have to ignore the TravisCI failures for now.

**Comment by lukeyeager** [comment]
Closing to create a new pull request with all new layers (Python and C++)

**Pull request closed without merging**
